language: java
jdk:
  - openjdk8

#Travis CI를 어느 브랜치가 푸시 될 때 수행할지 지정한다. 현재 옵션은 오직 master 브랜치에 push될 떄만 수행한다.
branches:
  only:
    - master

#접근권한이 아닌 실행권한이 없어서 추가해주는 코드, 아님 gradlew에 실행권한을 추가하고 github에 올리는 방법도 있다.
before_install:
  - chmod +x gradlew

# Travis CI 서버의 HOME
# 그레이들을 통해 의존성을 받게 되면 이를 해당 디렉토리에 캐시하여, 같은 의존성은 다음 배포 때부터 다시 받지 않도록 설정한다.
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# master브랜치에 푸시 되었을 떄 수행하는 명령어다. 여기서 프로젝트 내부에 둔 gradlew을 통해 clean&build를 수행한다.
script: "./gradlew clean build"


#Travis CI에서 빌드하여 만든 Jar파일을 S3에 올릴 수 있도록 코드를 추가한다.addons:
before_deploy:
  - zip -r springboot-webservice *
  - mkdir -p deploy
  - mv springboot-webservice.zip deploy/springboot-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: free-springboot-webservice-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: free-springboot-webservice-build
    key: freelec-springboot2-webservice.zip
    bundle_type: zip
    application: freelec-springboot2-webservice
    deployment_group: freelec-springboot2-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true


# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - cbq3737@naver.com
